services:
  db:
    image: postgres:17
    container_name: database
    environment:
      - POSTGRES_USER=aterrizar_ya
      - POSTGRES_PASSWORD=aterrizar_ya_password
      - POSTGRES_DB=database_aterrizar_ya
    ports:
      - 5432:5432
    volumes:
      - "./psql_data:/db-data:/var/lib/postgresql/data"