name: Deploy Static Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: npm install

      - name: Generar build
        run: npx serve -s -l 8000

      - name: Deploy en GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Publicar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2